// Generator function named "reverso" that takes a list as a parameter
function* reverso(lista) {
    // Start from the last index of the list and move backwards to index 0
    for (let i = lista.length - 1; i >= 0; i--) {
        // Yield each element one by one in reverse order
        yield lista[i];
    }
}

// Use a for...of loop to iterate over the values generated by reverso()
// Calling reverso(["x", "y", "z"]) will generate "z", then "y", then "x"
for (let item of reverso(["x", "y", "z"])) {
    // Print each generated item to the console
    console.log(item);
}
